blog/api/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$',views.PostListApiView.as_view(),name='post_list'),
    url(r'^(?P<pk>\d+)$',views.PostApiView.as_view(),name='post_rud'),
    url(r'^d/(?P<pk>\d+)$',views.DestroyApiView.as_view(),name='post_d'),

]

blog/urls.py
from django.conf.urls import url, include
from blog import views
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import TemplateView

app_name='blog'
urlpatterns=[
    url(r'^home/',views.GetAdd,name="index"),
    url(r'^post/',views.post,name='post'),
    url(r'^register/',views.register,name='register'),
    url(r'^delete/(?P<pk>[0-9]+)/(?P<author>\D+)//(?P<aut>\D+)/$',views.delete,name='delete'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^accounts/',include("django.contrib.auth.urls"), name='accounts'),
#    url(r'^password_change/$',PasswordChangeView.as_view(),name='password_change'),
    #url(r'^changed/',views.contact,name='password_change_done'),
    url(r'^search/',views.search,name='search'),
    url(r'^apis/', views.api_doc, name='api_doc'),
    url(r'^api/posts/$',views.post_list_api,name='list_api_view'),
    url(r'^api/post/(?P<pk>[0-9]+)/$',views.post_detail_api,name='detail_api_view'),
    #url(r'^home/', views.home),
    #url(r'^home/', views.HomeView.as_view(),name="home"),
    url(r'^$', views.PostListView.as_view(),name="home"),
    url(r'^post_detail/(?P<pk>\d+)', views.PostDetailView.as_view(), name='detail'),
    url(r'^add_detail/(?P<pk>\d+)', views.AddDetailView.as_view(), name='adddetail'),
    #url(r'^about/', views.about),
    url(r'^about/', TemplateView.as_view(template_name='about.html'),name='about'),
    url(r'^contact/', views.contact,name="contact"),
    #url(r'^contact/',views.contact)
    url(r'^apii/',include("blog.api.urls",namespace='blogapi')),
]

chat/alpha/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.Login, name='login'),
    #url(r'^admin/', admin.site.urls),
    url(r'^login/$', views.Login, name='login'),
    url(r'^logout/$', views.Logout, name='logout'),
    url(r'^home/$', views.Home, name='home'),
    url(r'^post/$', views.Post, name='post'),
    url(r'^messages/$', views.Messages, name='messages'),

    url(r'^test/$', views.test, name='test'),
]

def __unicode__(self):
   return self.message

mydjango/urls.py
from blog.views import *
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls import url, include

from django.contrib import admin
from django.template.context_processors import static
from mydjango import settings
from patterns import patterns
from django.conf.urls.static import static
admin.autodiscover()
from django.conf.urls import include, url
from django.contrib import admin
from crypto.views import get_crypto


admin.site.site_header='Django Blog Admin Panel'
admin.site.site_title='Blog Admin Panel'
admin.site.index_title='Dblog Administration'

urlpatterns = [
    # here we are not using pattern module like in previous django versions
    url(r'^admin/', include(admin.site.urls)),
    url(r'',include("blog.urls")),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'',include("business.urls")),
    url(r'',include("chat.urls")),
    url(r'cryp/',include("crypto.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models import CASCADE

from django.utils import timezone

class PublishManager(models.Manager):
    def get_queryset(self):
        return super(PublishManager,self).get_queryset() \
            .filter(status='published').order_by('-created')

class Contact(models.Model):
    email=models.EmailField()
    subject=models.CharField(max_length=200)
    body=models.TextField()
    def __str__(self):
        return "{} in ({})".format(self.email, self.subject, self.body)


class Post(models.Model):
    STATUS_CHOICES=(
        ('draft','Draft'),
        ('published','Published')
    )
    title=models.CharField(max_length=150)
    location=models.CharField(max_length=300)
    author=models.ForeignKey('auth.User',related_name='blog_posts')
    duration=models.CharField(max_length=20)
    budget=models.CharField(max_length=100)
    attraction=models.CharField(max_length=1000)
    maxattitude=models.CharField(max_length=50)
    bestseason=models.CharField(max_length=500)
    experiencerequired=models.CharField(max_length=1000)
    carrying=models.CharField(max_length=1000)
    hotels=models.CharField(max_length=2000)
    body=models.TextField()
    publish=models.DateTimeField(default=timezone.now)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    photo=models.ImageField(blank=True)
    photo1=models.ImageField(blank=True)
    photo2=models.ImageField(blank=True)
    photo3=models.ImageField(blank=True)
    status=models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    #managers
    objects=models.Manager()
    published=PublishManager()
    class Meta:
        ordering=('-publish',)

    def __str__(self):
        return self.title


class Comments(models.Model):
    name=models.CharField(max_length=20)
    email=models.EmailField(blank=True,null=True)
    post_id=models.ForeignKey("Post",related_name='post_comments', on_delete=CASCADE)
    comment_body=models.TextField(max_length=200)

    def __str__(self):
        return "{} in ({})".format(self.name,self.post_id.title)



from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email=models.EmailField(null=True,blank=True)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

blog/forms.py
from blog.models import Comments, Post, Contact
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model=Comments
        fields=['name','email','comment_body']


class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','location','duration','budget','maxattitude','bestseason','experiencerequired','carrying','attraction','hotels','body','publish','photo','photo1','photo2','photo3']

class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields=['email','subject','body']



from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email=forms.EmailField(help_text='Enter a valid email')

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2','email' )

blog/api/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import generics
from blog.models import Post
from .serializers import PostSerializer

class PostListApiView(generics.ListAPIView):
    lookup_field = 'pk'
    serializer_class = PostSerializer
    queryset = Post.published.all()

class PostApiView(generics.RetrieveUpdateAPIView):
    lookup_field = 'pk'
    serializer_class = PostSerializer
    queryset = Post.published.all()

class DestroyApiView(LoginRequiredMixin,generics.RetrieveDestroyAPIView):
    lookup_field = 'pk'
    serializer_class = PostSerializer
    queryset = Post.published.all()

# class PostDetailApiView(generics.RetrieveAPIView):
#     lookup_field = 'pk'
#     serializer_class = PostSerializer
#
#     def get_queryset(self):
#         pk=self.kwargs.get('pk')
#         return Post.published.get(pk=pk)

blog/views.py
from msilib.schema import ListView

from blog.forms import CommentForm, PostForm, ContactForm,SignUpForm
from blog.serializers import PostSerializer
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import *
from blog.models import Post, Comments
from business.models import Add
# Create your views here.
from django.urls import reverse
from django.views.generic import TemplateView,ListView,DetailView
from mydjango.settings import DEFAULT_FROM_EMAIL
from rest_framework import status
from rest_framework.renderers import JSONRenderer


def index(request):
    he={'sujan':[1,2,3,4,5,6,7,8,9,10]}
    return render(request,template_name='index.html',context=he)





def home(request):
    #object_list=Post.objects.order_by('-created_date')
    #count=object_list.count()
    #ct={
    #     "object_list":object_list,"count":count
    # }
    return render(request,template_name='home.html',context={})

def about(request):
    return render(request,template_name='about.html',context={})

def contact(request):
    form = ContactForm(request.POST)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("http://127.0.0.1:8000/home/")
    else:
        return render(request, 'contact.html', {"form":form})




def get_one_post(request,*args,**kwargs):
    p=kwargs.get('pop')
    one_post=get_object_or_404(Post,pk=p)

    ctx={"one_post":one_post
    }
    return render(request,'post_detail.html',context=ctx)

class HomeView(TemplateView):
    def get(self,request,*args,**kwargs):
        object_list = Post.objects.order_by('-created_date')
        count = object_list.count()
        ct = {
            "object_list": object_list, "count": count
        }
        return render(request, template_name='home.html', context=ct)

# class ContactView(TemplateView):
#     def get(self,request,*args,**kwargs):
#         return render(request, template_name='contact.html', context={})


class PostListView(ListView):
    model = Post
    context_object_name = "posts_list"
    #queryset = Post.objects.order_by('-created')
    #Option 2
    # def get_queryset(self):
    #     return Post.objects.order_by('-created_date')

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        # context['object_list'] = Post.objects.order_by('-created')
        #context['posts_list'] = Post.objects.filter(status='published').order_by('-created')
        context['posts_list'] = Post.published.all()

        #context['count'] = context['object_list'].count()
        return context

    template_name='blog/home.html'

class PostDetailView(DetailView):
    model = Post
    context_object_name = 'one_post'
    template_name = 'blog/post_detail.html'

    def get(self,request,*args,**kwargs):
        p = kwargs.get('pk')
        try:
            one_post = Post.objects.get(
                Q(pk=p) & Q(status='published'))
        except:
            raise Http404
        #comments=Comments.objects.filter(post_id=one_post)
        comments=one_post.post_comments.all()

        #prepare Form
        comment_form=CommentForm()

        ctx = {"one_post": one_post,
               'comments':comments,
               "comment_form":comment_form
                   }
        return render(request, 'blog/post_detail.html', context=ctx)


    def post(self,request,*args,**kwargs):
        comments=CommentForm(data=request.POST)
        if comments.is_valid():
            new_comment=comments.save(commit=False)
            post_comment=get_object_or_404(Post,pk=kwargs.get('pk'))
            new_comment.post_id=post_comment
            new_comment.save()
            return redirect('blog:detail',pk=post_comment.pk)
    # def get_context_data(self, **kwargs):
    #     context=super(PostDetailView,self).get_context_data(**kwargs)
    #     context['comment']=Comments.objects.all()
    #     return context
@login_required
def post(request):
    if request.method=='POST':
        com = PostForm(request.POST,request.FILES)
        if com.is_valid():
            post=com.save(commit=False)
            post.author=request.user
            post.save()
            return redirect('blog:home')
    else:
        post_list = PostForm()
        ctx = {'post_list': post_list

               }
    return render(request,template_name='post.html',context=ctx)


def search(request,*args,**kwargs):
    query=request.POST.get('searchquery')
    data=Post.objects.filter(Q(title__contains=query) | Q(body__contains=query)).filter(status='published')
    count=data.count()
    ctx={
        'result':data,'count':count
    }
    return render(request,'blog/searchresult.html',context=ctx)
@login_required
def register(request):
    if request.method=='POST':
        user_form=UserCreationForm(data=request.POST)
        if user_form.is_valid():
            new_user=user_form.save()
            return redirect('blog:login')
    else:
        form=UserCreationForm()
    return render(request,'blog/register.html',{'form':form})

class JSONResponse(HttpResponse):
    def __init__(self,data,*args,**kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type']='application/json'
        super(JSONResponse,self).__init__(content,**kwargs)

def post_list_api(request):
    if request.method == 'GET':
        posts = Post.published.all()
        post_serializer= PostSerializer(posts,many=True)
        return JSONResponse(post_serializer.data)

def post_detail_api(request,pk):
    try:
        one_post=Post.published.get(pk=pk)
    except Post.DoesNotExist:
        return HttpResponse(status=status.HTTP_404_NOT_FOUND)

    if request.method == "GET":
        post_detail_serializer=PostSerializer(one_post)
        return JSONResponse(post_detail_serializer.data)


def api_doc(request):
    return render(request,template_name='blog/api_doc.html')



from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('blog:home')
    else:
        form = SignUpForm()
    return render(request,'blog/signup.html', {'form': form})











def delete(request,pk,author,aut):
    if author==aut:
        Post.objects.filter(pk=pk).delete()
        return HttpResponseRedirect("http://127.0.0.1:8000/home/")
    else:
        return HttpResponseRedirect("http://127.0.0.1:8000/home/")


def GetAdd(request):
    value=Add.objects.all()
    return render(request,"index.html",{'value':value})


class AddDetailView(DetailView):
    model = Add
    context_object_name = 'one_post'
    template_name = 'blog/add_detail.html'

    def get(self,request,*args,**kwargs):
        p = kwargs.get('pk')
        try:
            one_post = Add.objects.get(pk=p)
        except:
            raise Http404
        #comments=Comments.objects.filter(post_id=one_post)


        #prepare Form


        ctx = {"one_post": one_post,
                   }
        return render(request, 'blog/add_detail.html', context=ctx)

blog/templates/blog/add_detail.html
{%  extends 'base.html' %}
{% load blog_tags %}

{%  block bodyBlock %}
    <h2>Title : {{ one_post.name}}</h2>
    <a>Location : {{ one_post.location }}<br>
    <a>Phone : {{ one_post.phone }}<br/>
        <a>Price Per Person : {{ one_post.price }}<br/>
            <a>Special Offers : {{ one_post.offers }}<br/>
                <a>Hotel Facilities : {{ one_post.hotelfacilities }}<br/>
                    <a>Room Facilities : {{ one_post.roomfacilities }}<br>
                        <a>Inhouse Facilities : {{ one_post.inhousefacilities }}<br>
                            <img src="{{ one_post.photo.url }}" width="500px" height="500px"/>
                            <img src="{{ one_post.photo1.url }}" width="500px" height="500px"/>


</a>











{% endblock %}

blog/templates/blog/api_doc.html
{% extends 'base.html' %}

{% block bodyBlock %}
<h1>API Documentation</h1>
    <p class ='text-info'>HTTP GET</p>
    <table class="table table-stripped">

        <th>
        <th><td>EndPoint</td></th>
            <th><td>Description</td></th>

    <tbody>
    <tr>
        <td><pre>/api/posts</pre></td>
        <td>Get all Published post</td>
    </tr>
    <tr>
        <td><pre>/api/post/(int:pk)</pre></td>
        <td>Get one post</td>
    </tr>
    </tbody>
    </>
{% endblock bodyBlock %}

blog/templates/blog/change_list.html
{% extends 'admin/change_list.html' %}
{% block object-tools %}
<div>
<button class="btn-danger">Delete all at once</button>
<button class="btn btn-danger">Something</button>


</div>
    {{ block.super }}
{% endblock object-tools %}

blog/templates/blog/home.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load pagination_tags %}

{% block titleBlock %}
    home | {{block.super}}
{% endblock %}

{% block bodyBlock %}
    {%  autopaginate posts_list 3 %}
    <div class="row">
        <div class="col-8">
            <div class="post">
                {# {{ posts_list | length }} #}
                {% count %} post entries are found....
                {% for each in posts_list %}<br/>
                    <img src="{{ each.photo.url }}" width="120px" height="60px"/>
                    <h3 style="color: chartreuse"><a href="{% url 'blog:detail' pk=each.pk %}"> Title : {{ each.title |  capitalize | cut:' '  }}</a></h3>
                    <small style="color: blueviolet">Date : {{ each.created | date:'D d M Y'}}</small><br/>
                    <big> Content : {{ each.body | truncatechars:'15' }}
                    </big><hr>
                {% endfor %}

            </div>
        </div>
        <div class="col-4">
            <div class="post">
                <h4>Latest Post :</h4>
                {% get_latest 4 %}
            </div>
        </div>
    </div>
    <div>{% paginate %}</div>
{% endblock %}

blog/templates/blog/latest.html
<ul>
    {% for blog in latest_blogs %}
    <li><a href="{% url 'blog:detail' pk=blog.pk %}">{{ blog }}</a> </li>
    {% endfor %}
</ul>

blog/templates/blog/post_detail.html
{%  extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% load ratings %}

{%  block bodyBlock %}
    <h1>Destination Name : {{ one_post.title }}</h1>
    <small>Post By : <b>{{ one_post.author }}</b> in {{ one_post.created }} </small><br>
    <big><b>Location :</b> {{ one_post.location }}</big><br>
    <big><b>Max Attitude : </b>{{ one_post.maxattitude }}</big><br>
    <big><b>Best Season : </b>{{ one_post.bestseason }}</big><br>
    <big><b>Budget : </b>{{ one_post.budget }}</big><br>
    <big><b>Major Attractions : </b>{{ one_post.attaraction }}</big><br>
    <big><b>Experience Required : </b>{{ one_post.experiencerequired }}</big><br>
    <big><b>Carrying Materials : </b>{{ one_post.carrying }}</big><br>
    <big><b>Hotels : </b>{{ one_post.hotels }}</big><br>
    <big><b>Trip Entire Detail : </b>{{ one_post.body }}</big><br/><br/>
    <img src="{{ one_post.photo.url }}" width="500px" height="500px"/>
    <img src="{{ one_post.photo1.url }}" width="500px" height="500px"/>

</br>
<br>
{% ratings one_post %}






 {% if user.is_authenticated %}
<a href="{% url 'blog:delete' one_post.pk one_post.author user.username %}">Delete</a>
{% endif %}


<br/>
    <br/>
<br/>
    <h5>Comments</h5>
    {% for co in comments %}
        Username : <b>{{ co.name }}</b><br/>
        Comment : <b>{{ co.comment_body }}</b><hr>
        {% empty %}
            <h6>No comments yet</h6>
    {% endfor %}<br>
{% similar one_post.title one_post.pk as similar_posts %}
    <ul>
    <h4>Similar Post</h4>
    {% for similar in similar_posts %}
    <li><a href="{% url 'blog:detail' pk=similar.pk %}" >{{ similar.title }}</a></li>
    {% endfor %}

    </ul>


    <form action="" method="POST">{% csrf_token %}

<fieldset>
  <legend>Add Comment</legend>
    {{ comment_form.as_p }}
    <input type="submit" class="btn btn-success" value="Add Comment">
    </fieldset>
    </form>

{% endblock %}

blog/templates/blog/rating.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="rabidRating-{{rating_key}}-{{rating}}_{{max_stars}}" class="rabidRating ratingUnrated">
    <div class="wrapper">
        <span class="ratingFill" style="width:{{percent}}%;">
            <span class="ratingStars"></span>
        </span>
    </div>
    <div id="rabidRating-{{rating_key}}-description" class="ratingText">
        {{rating}}/{{max_stars}} stars ({{total_votes}} votes)
    </div>
</div>
</body>
</html>

blog/templates/blog/register.html
{% extends 'base.html' %}

{% block bodyBlock %}
    <h1>Fill the following form to Create a User</h1>
<form action="" method="POST">
{% csrf_token %}
{{ form.as_p }}
<button class="btn btn-primary">Login</button>

</form>
{% endblock bodyBlock %}

blog/templates/blog/searchresult.html
{% extends 'base.html' %}

{% block bodyBlock %}

{% for res in result %}<ul>
    <li><a href="{% url 'blog:detail' pk=res.pk %}">{{ res }}</a></li>
    </ul>
    {% empty %}
    <P>No Results Found</P>
    {% endfor %}
    {{ count }} articles found
{% endblock bodyBlock %}

blog/templates/blog/signup.html
{% extends 'base.html' %}

{% block bodyBlock %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}

    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}

        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit" href="{% url 'blog:login' %}?next={% url 'blog:login' %}">Sign up</button>
  </form>
{% endblock %}