blog/urls.py
from django.conf.urls import url, include
from blog import views
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import TemplateView

app_name='blog'
urlpatterns=[
    url(r'^home/',views.GetAdd,name="index"),
    url(r'^post/',views.post,name='post'),
    url(r'^register/',views.register,name='register'),
    url(r'^delete/(?P<pk>[0-9]+)/(?P<author>\D+)//(?P<aut>\D+)/$',views.delete,name='delete'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^accounts/',include("django.contrib.auth.urls"), name='accounts'),
#    url(r'^password_change/$',PasswordChangeView.as_view(),name='password_change'),
    #url(r'^changed/',views.contact,name='password_change_done'),
    url(r'^search/',views.search,name='search'),
    url(r'^apis/', views.api_doc, name='api_doc'),
    url(r'^api/posts/$',views.post_list_api,name='list_api_view'),
    url(r'^api/post/(?P<pk>[0-9]+)/$',views.post_detail_api,name='detail_api_view'),
    #url(r'^home/', views.home),
    #url(r'^home/', views.HomeView.as_view(),name="home"),
    url(r'^$', views.PostListView.as_view(),name="home"),
    url(r'^post_detail/(?P<pk>\d+)', views.PostDetailView.as_view(), name='detail'),
    url(r'^add_detail/(?P<pk>\d+)', views.AddDetailView.as_view(), name='adddetail'),
    #url(r'^about/', views.about),
    url(r'^about/', TemplateView.as_view(template_name='about.html'),name='about'),
    url(r'^contact/', views.contact,name="contact"),
    #url(r'^contact/',views.contact)
    url(r'^apii/',include("blog.api.urls",namespace='blogapi')),
]

business/urls.py
from django.conf.urls import url, include
from business import views
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import TemplateView

app_name='bus'
urlpatterns=[
    url(r'^busi/$', views.business,name='index'),
    url(r'^adds/$', views.adds,name='adds'),
    url(r'^dashboard/$', views.login,name='dashboard'),




]

chat/alpha/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.Login, name='login'),
    #url(r'^admin/', admin.site.urls),
    url(r'^login/$', views.Login, name='login'),
    url(r'^logout/$', views.Logout, name='logout'),
    url(r'^home/$', views.Home, name='home'),
    url(r'^post/$', views.Post, name='post'),
    url(r'^messages/$', views.Messages, name='messages'),

    url(r'^test/$', views.test, name='test'),
]

def __unicode__(self):
   return self.message

chat/urls.py
from django.conf.urls import url, include

from django.contrib.auth.views import PasswordChangeView
from django.views.generic import TemplateView
from chat.views import *
from chat import views
app_name='chat'
urlpatterns=[
    url(r'^in/$',views.host,name='ind'),
    url(r'^ch/',views.sea,name='srh'),
]

mydjango/urls.py
from blog.views import *
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls import url, include

from django.contrib import admin
from django.template.context_processors import static
from mydjango import settings
from patterns import patterns
from django.conf.urls.static import static
admin.autodiscover()
from django.conf.urls import include, url
from django.contrib import admin
from crypto.views import get_crypto


admin.site.site_header='Django Blog Admin Panel'
admin.site.site_title='Blog Admin Panel'
admin.site.index_title='Dblog Administration'

urlpatterns = [
    # here we are not using pattern module like in previous django versions
    url(r'^admin/', include(admin.site.urls)),
    url(r'',include("blog.urls")),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'',include("business.urls")),
    url(r'',include("chat.urls")),
    url(r'cryp/',include("crypto.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/css/cs3.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'styles.css' %}">
<style>
    body{
        background-color:#f2dede;
    }
</style>

templates/css/js.html
{% load staticfiles %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static '' %}">
</script>

templates/css/nav.html
{% load blog_tags %}
                    {% if user.is_authenticated %}
                        <h1 class="text.primary" style="text-align: center">Welcome : {{ user.username }}</h1>
                    {% endif %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'blog:index' %}">{% blog_name %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/contact">Contact</a>
            </li>
        <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:api_doc' %}">Api Documentation</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:about' %}">About</a>
            </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
                <a class="nav-link" href="{%  url 'chat:ind' %}">Chat</a>
            </li>
        {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:index' %}">View Add</a>
            </li>

            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    More
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

 {% if user.is_authenticated %}
     {% else %}
                    <a class="dropdown-item" href="{% url 'bus:index' %}">Business Signup</a>
                <a class="dropdown-item" href="{% url 'bus:dashboard' %}">Business Login</a>
{% endif %}
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="/post">Add Post</a>
                        <a class="dropdown-item" href="{% url 'blog:password_change' %}">Change password</a>
                        <a class="dropdown-item" href="{% url 'blog:logout' %}?next={% url 'blog:home' %}">Logout</a>
                    {% else %}
                        <a class="dropdown-item" href="{% url 'blog:login' %}?next={% url 'blog:home' %}">Login</a>
<a class="dropdown-item" href="{% url 'blog:signup' %}">Signup</a>
                    {% endif %}

                </div>
            </li>


            <li class="nav-item">
                <form class="form-inline" method="post" action="{% url 'blog:search' %}">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2"  name="searchquery" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </li>
        </ul>
    </div>
</nav>

templates/css/slider.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box;}
body {font-family: Verdana, sans-serif;}
.mySlides {display: none;}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 1000px;
  position: relative;
  margin: auto;
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active {
  background-color: #717171;
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 1.5s;
  animation-name: fade;
  animation-duration: 1.5s;
}

@-webkit-keyframes fade {
  from {opacity: .4}
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4}
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .text {font-size: 11px}
}
</style>
</head>
<body>

<div class="slideshow-container">

<div class="mySlides fade">
  <div class="numbertext">1 / 8</div>
  <img src="{% static "annpurna.jpg" %}" style="width:100%;">
  <div class="text">Annapurna Base Camp</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">2 / 8</div>
  <img src="{% static "everest.jpg" %}" style="width:100%;">
  <div class="text">Everest Base Camp</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">3 / 8</div>
  <img src="{% static "ghorepani.jpg" %}" style="width:100%;">
  <div class="text">Ghorepani Poon Hill</div>
</div>

    <div class="mySlides fade">
  <div class="numbertext">4 / 8</div>
  <img src="{% static "kaptad.jpg" %}" style="width:100%;">
  <div class="text">Khaptad National Park</div>
</div>

    <div class="mySlides fade">
  <div class="numbertext">5 / 8</div>
  <img src="{% static "manage.jpg" %}" style="width:100%;">
  <div class="text">Manang Valley</div>
</div>

    <div class="mySlides fade">
  <div class="numbertext">6 / 8</div>
  <img src="{% static "panch.jpg" %}" style="width:100%;">
  <div class="text">Panch Pokhari</div>
</div>

    <div class="mySlides fade">
  <div class="numbertext">7 / 8</div>
  <img src="{% static "rara.jpg" %}" style="width:100%;">
  <div class="text">Rara Lake</div>
</div>

    <div class="mySlides fade">
  <div class="numbertext">8 / 8</div>
  <img src="{% static "tilicho.jpg" %}" style="width:100%;">
  <div class="text">Tilicho Lake</div>
</div>

</div>
<br>

<div style="text-align:center">
  <span class="dot"></span>
  <span class="dot"></span>
  <span class="dot"></span>
    <span class="dot"></span>
    <span class="dot"></span>
    <span class="dot"></span>
    <span class="dot"></span>
    <span class="dot"></span>
</div>
</body>
</html>
<script>
var slideIndex = 0;
showSlides();

function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    for (i = 0; i < slides.length; i++) {
       slides[i].style.display = "none";
    }
    slideIndex++;
    if (slideIndex > slides.length) {slideIndex = 1}
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";
    dots[slideIndex-1].className += " active";
    setTimeout(showSlides, 2000); // Change image every 2 seconds
}
</script>

</body>
</html>