blog/urls.py
from django.conf.urls import url, include
from blog import views
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import TemplateView

app_name='blog'
urlpatterns=[
    url(r'^home/',views.GetAdd,name="index"),
    url(r'^post/',views.post,name='post'),
    url(r'^register/',views.register,name='register'),
    url(r'^delete/(?P<pk>[0-9]+)/(?P<author>\D+)//(?P<aut>\D+)/$',views.delete,name='delete'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^accounts/',include("django.contrib.auth.urls"), name='accounts'),
#    url(r'^password_change/$',PasswordChangeView.as_view(),name='password_change'),
    #url(r'^changed/',views.contact,name='password_change_done'),
    url(r'^search/',views.search,name='search'),
    url(r'^apis/', views.api_doc, name='api_doc'),
    url(r'^api/posts/$',views.post_list_api,name='list_api_view'),
    url(r'^api/post/(?P<pk>[0-9]+)/$',views.post_detail_api,name='detail_api_view'),
    #url(r'^home/', views.home),
    #url(r'^home/', views.HomeView.as_view(),name="home"),
    url(r'^$', views.PostListView.as_view(),name="home"),
    url(r'^post_detail/(?P<pk>\d+)', views.PostDetailView.as_view(), name='detail'),
    url(r'^add_detail/(?P<pk>\d+)', views.AddDetailView.as_view(), name='adddetail'),
    #url(r'^about/', views.about),
    url(r'^about/', TemplateView.as_view(template_name='about.html'),name='about'),
    url(r'^contact/', views.contact,name="contact"),
    #url(r'^contact/',views.contact)
    url(r'^apii/',include("blog.api.urls",namespace='blogapi')),
]

mydjango/urls.py
from blog.views import *
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls import url, include

from django.contrib import admin
from django.template.context_processors import static
from mydjango import settings
from patterns import patterns
from django.conf.urls.static import static
admin.autodiscover()
from django.conf.urls import include, url
from django.contrib import admin
from crypto.views import get_crypto


admin.site.site_header='Django Blog Admin Panel'
admin.site.site_title='Blog Admin Panel'
admin.site.index_title='Dblog Administration'

urlpatterns = [
    # here we are not using pattern module like in previous django versions
    url(r'^admin/', include(admin.site.urls)),
    url(r'',include("blog.urls")),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'',include("business.urls")),
    url(r'',include("chat.urls")),
    url(r'cryp/',include("crypto.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models import CASCADE

from django.utils import timezone

class PublishManager(models.Manager):
    def get_queryset(self):
        return super(PublishManager,self).get_queryset() \
            .filter(status='published').order_by('-created')

class Contact(models.Model):
    email=models.EmailField()
    subject=models.CharField(max_length=200)
    body=models.TextField()
    def __str__(self):
        return "{} in ({})".format(self.email, self.subject, self.body)


class Post(models.Model):
    STATUS_CHOICES=(
        ('draft','Draft'),
        ('published','Published')
    )
    title=models.CharField(max_length=150)
    location=models.CharField(max_length=300)
    author=models.ForeignKey('auth.User',related_name='blog_posts')
    duration=models.CharField(max_length=20)
    budget=models.CharField(max_length=100)
    attraction=models.CharField(max_length=1000)
    maxattitude=models.CharField(max_length=50)
    bestseason=models.CharField(max_length=500)
    experiencerequired=models.CharField(max_length=1000)
    carrying=models.CharField(max_length=1000)
    hotels=models.CharField(max_length=2000)
    body=models.TextField()
    publish=models.DateTimeField(default=timezone.now)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    photo=models.ImageField(blank=True)
    photo1=models.ImageField(blank=True)
    photo2=models.ImageField(blank=True)
    photo3=models.ImageField(blank=True)
    status=models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    #managers
    objects=models.Manager()
    published=PublishManager()
    class Meta:
        ordering=('-publish',)

    def __str__(self):
        return self.title


class Comments(models.Model):
    name=models.CharField(max_length=20)
    email=models.EmailField(blank=True,null=True)
    post_id=models.ForeignKey("Post",related_name='post_comments', on_delete=CASCADE)
    comment_body=models.TextField(max_length=200)

    def __str__(self):
        return "{} in ({})".format(self.name,self.post_id.title)



from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email=models.EmailField(null=True,blank=True)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

templates/about.html
{% extends 'base.html' %}

{% block titleBlock %}
        about | {{block.super}}
        {% endblock %}

{% block bodyBlock %}
    <h1>Welcome to About Page</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_tags %}
<html lang="en">
<head>
{% load static %}




<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

    <meta charset="UTF-8">
    <title>{% block titleBlock %}
        base
    {% endblock %}</title>
</head>
<body>
{% include 'css/slider.html' %}
{% include 'css/nav.html' with blogname="*" %}
{% include 'css/cs3.html' %}
{% include 'css/js.html' %}

<div class="row">
    <div class="container">

        <h1 align="center" style="color:red " > Welcome to exploreNepal</h1>
        {% block bodyBlock %}
        {% endblock %}
    <h4 style="text-align: center">{% footer %}</h4>
    </div></div>

</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block titleBlock %}
        contact | {{block.super}}
        {% endblock %}

{% block bodyBlock %}
    <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">

    </form>

{% endblock %}

templates/crypto_currency.html
{%  extends 'base.html' %}

{% block bodyBlock %}
    <table class="table table-bordered table-stripped table-hover table-sm">
    <thead align="center">
    <tr>
    <th>Rank</th>
    <th>Name</th>
    <th>ID</th>
    <th>Symbol</th>
    <th>Price in USD</th>
    <th>Max Supply</th>
    <th>Last Update</th>
    </tr>

    </thead>

    <tbody align="center">

    {% for each in data %}
        <tr class="{% if each.percent_change_24h.0 == "-" %} text-danger
        {% else %}text-sucess
        {% endif %}">
        <td>{{ each.rank }}</td>
        <td>{{ each.name }}</td>
        <td>{{ each.id }}</td>
        <td>{{ each.symbol }}</td>
        <td>{{ each.price_usd }}</td>
        <td>{{ each.max_supply }}</td>
        <td>{{ each.last_updated }}</td>


        </tr>

    {% endfor %}


    </tbody>


    </table>



{% endblock %}

templates/email_template.html
By={{ email_id }}

Subject={{ subject }}

Body={{ body }}

templates/index.html
{% extends 'base.html' %}
{% load blog_tags %}


{% block titleBlock %}
    home | {{block.super}}
{% endblock %}

{% block bodyBlock %}

    <div class="row">
        <div class="col-8">
            <div class="post">
                {# {{ posts_list | length }} #}

                {% for each in value %}
                    <img src="{{ each.photo.url }}" width="120px" height="60px"/>
                    <h3 style="color: chartreuse"><a href="{% url 'blog:adddetail' pk=each.pk %}"> Hotel Name : {{ each.name |  capitalize | cut:' '  }}</a></h3>
                    <big> Location : {{ each.location| truncatechars:'15' }}
                    </big><hr>
                {% endfor %}

            </div>
        </div>
        <div class="col-4">
            <div class="post">
                <h4>Latest Post :</h4>
                {% get_latest 4 %}
            </div>
        </div>
    </div>

{% endblock %}

templates/post.html
{% extends 'base.html' %}
{% block bodyBlock %}
<form action="" method="post" class="form-horizontal" enctype="multipart/form-data">
    {% csrf_token %}
    {{ post_list.as_p }}
    <input type="submit" class="btn btn-success" value="Add Post">

</form>
{% endblock %}